sudo: required
language: node_js
cache:
  directories:
    - node_modules
    - packages/front-end/node_modules
    - packages/smart-contracts/node_modules
    - packages/shared/node_modules
notifications:
  email: false
node_js:
  - '11.0.0'
env:
#  - TASK=lint
  - TASK=contracts:test
  - TASK=frontend:test
before_script:
  - testrpc > /dev/null &
  - sleep 5
script:
  - travis_wait 60 npm run $TASK
#after_success:
#  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
