version: 2
jobs:
  build:
    #machine: true
    working_directory: ~/CherrySwap
    docker:
      - image: circleci/python:3-node
    steps: 
      - checkout 
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Activate venv
          command: python3 -m venv venv && . venv/bin/activate
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            #- ~/.cache/yarn            
      - run:
          name: test solidity smart contracts
          command: npm run test
      #- run:
      #    name: code-coverage
      #    command: './node_modules/.bin/nyc report --reporter=text-lcov'
      #- store_artifacts:
      #    path: test-results.xml
      #    prefix: tests
      #- store_artifacts: 
      #    path: coverage
      #    prefix: coverage
      #- store_test_results:
      #    path: test-results.xml