version: 2
jobs:
  build:
    working_directory: ~/CherrySwap
    docker:
      - image: circleci/node:10.18.0
      - image: trufflesuite/ganache-cli
        command: ganache-cli --deterministic -e 300 -p 8545 -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --accounts 30
    steps: 
      - checkout 
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test solidity smart contracts
          command: cd ./packages/smart-contracts/ && yarn run test
      #- run:
      #    name: code-coverage
      #    command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts: 
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml